Add onnx support
iterative/mlem pull request #292
Opened 2022-06-09 16:42 UTC by maheshambule

- Adds ONNX support. This is WIP.
- Tested save, apply and serve APIs for basic sklearn models
- TODOs are listed in code

2022-06-13 13:03 UTC, mike0sv requested changes
Had some questions and suggestions, but looks great overall.

2022-06-13 13:03 UTC, mike0sv commented on tests/contrib/test_onnx.py
> +# Copyright 2019 Zyfra
This is not needed :)

2022-06-20 15:21 UTC, omesser requested changes

2022-06-20 15:21 UTC, omesser commented on mlem/contrib/onnx.py
> +        for input_data in pred_onnx:
```suggestion
        for output_data in pred_onnx:
```
😉

2022-06-23 11:03 UTC, omesser approved these changes

2022-06-24 17:52 UTC, mike0sv commented on mlem/contrib/onnx.py
> +from functools import cached_property
cached_property is not available in python 3.7

2022-06-24 20:36 UTC, mike0sv reviewed
Can you resolve conflicts and make it pass all the checks?

2022-06-27 14:17 UTC, aguschin requested changes

2022-06-29 11:52 UTC, aguschin commented
@maheshambule, most of the tests pass 🎉, but looks like there are couple of easy tests that needs fixing. Could you please TAL?

2022-06-29 12:54 UTC, aguschin approved these changes

2022-06-30 13:53 UTC, aguschin commented
Yes, it was enough to retry the test. We need to mark some tests flaky to retry them instead of failing CI, #326 
Great work on supporting onnx btw! @mike0sv, do you want to TAL or I can go ahead and merge this?

2022-07-04 05:03 UTC, aguschin commented
Sorry @maheshambule, missed your last message. Just triggered the CI :)

2022-07-04 14:06 UTC, aguschin approved these changes

2022-07-04 17:04 UTC, omesser approved these changes

2022-07-05 07:49 UTC, aguschin commented on tests/contrib/test_pandas.py
> +    assert all([a == b for a, b in zip(actual, expected)])
```suggestion
    assert all(a == b for (a, b) in zip(actual, expected))
```

2022-07-05 07:49 UTC, aguschin commented on tests/contrib/test_pandas.py
> +    assert all([a == b for a, b in zip(actual, expected)])
to satisfy pylint

2022-07-05 09:55 UTC, merged